name: 🐛 Bug Report
description: Create a report to help us improve Web Share API Tester
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of web-share-tester are you running?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Node.js
        - Browser
        - Both
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: "e.g., 20.9.0"

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the server with 'npx web-share-tester'
        2. Open browser to localhost:3001
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: console-output
    attributes:
      label: Console Output
      description: Please copy and paste any relevant console output or error messages.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, browser version, OS, etc.)

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have ideas on how to fix this, please share them here.