name: ❓ Question
description: Ask a question about Web Share API Tester
title: "[Question]: "
labels: ["question", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation first, then provide details below.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
        - label: This is not a bug report (use the bug template instead)
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Installation/Setup
        - Usage/How-to
        - Integration
        - Configuration
        - Best Practices
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup, use case, or what you're trying to achieve.
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any specific requirements or constraints?

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: If relevant, provide details about your environment.
      placeholder: |
        - OS: 
        - Node.js version:
        - Browser:
        - Package version:

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context that might be helpful.