name: Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        npm run build
        timeout 10s npm run server &
        SERVER_PID=$!
        sleep 5
        curl -f http://localhost:3001/api/health || echo "Health check failed"
        kill $SERVER_PID 2>/dev/null || true

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create release summary
      run: |
        echo "## 🎉 Release Published Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "- **Package**: web-share-tester@${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **NPM**: https://www.npmjs.com/package/web-share-tester" >> $GITHUB_STEP_SUMMARY
        echo "- **Install**: \`npm install web-share-tester --save-dev\`" >> $GITHUB_STEP_SUMMARY